permalink: pretty

baseurl: /https://github.com/busted-minds/busted-minds.github.io



url: "https://busted-minds.github.io" # the base hostname & protocol for your site

plugins:

  - jekyll-sitemap

